Part A

In [ ]:
import numpy as np

# Given matrices
Resources_Matrix = np.array([[10, 15], [20, 25], [30, 35]])  # 3x2 (teams x months)
Allocation_Factors = np.array([[1.1, 0.9], [1.0, 1.2]])  # 2x2 (adjustment factors)

# Matrix multiplication to calculate total resource allocation
result = np.dot(Resources_Matrix, Allocation_Factors)
print(result)


[[26. 27.]
 [47. 48.]
 [68. 69.]]


In [ ]:
Shift_A_Production = np.array([[10, 15, 20, 25, 30, 35, 40], [12, 18, 24, 28, 33, 38, 42], [14, 19, 23, 27, 32, 36, 41]])  # 3 factories x 7 days
Shift_B_Production = np.array([[8, 12, 18, 22, 28, 34, 37], [9, 13, 19, 23, 29, 36, 40], [10, 14, 21, 26, 31, 37, 43]])

Total_Production = Shift_A_Production + Shift_B_Production  # Element-wise addition
print(Total_Production)

[[18 27 38 47 58 69 77]
 [21 31 43 51 62 74 82]
 [24 33 44 53 63 73 84]]


In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

forecast_values = np.array([0.5, 1.5, 2.5, 3.5])
sigmoid_output = sigmoid(forecast_values)
print(sigmoid_output)

[0.62245933 0.81757448 0.92414182 0.97068777]


In [ ]:
def sigmoid_gradient(x):
    return sigmoid(x) * (1 - sigmoid(x))

gradient = sigmoid_gradient(forecast_values)
print(gradient)

[0.23500371 0.14914645 0.07010372 0.02845302]


Part C

In [ ]:
import numpy as np

# Sigmoid and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# ReLU and its derivative
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

# Training Data
X = np.array([[20, 3, 4], [15, 5, 3], [30, 2, 2], [25, 4, 1], [35, 2, 3]])  # Input
Y = np.array([[18], [20], [22], [25], [30]])  # Output

# Initialize weights and biases
W1 = np.random.randn(3, 3) * 0.01
b1 = np.zeros((1, 3)) # Corrected shape from (3, 1) to (1, 3)
W2 = np.random.randn(1, 3) * 0.01
b2 = np.zeros((1, 1))

# Learning rate
learning_rate = 0.01

# Training loop
for epoch in range(10000):  # Train for 10,000 iterations
    # Forward propagation
    Z1 = np.dot(X, W1) + b1
    A1 = relu(Z1)
    Z2 = np.dot(A1, W2.T) + b2
    A2 = sigmoid(Z2)

    # Loss function (Mean Squared Error)
    loss = np.mean((A2 - Y) ** 2)

    # Backward propagation
    dA2 = 2 * (A2 - Y)  # Derivative of MSE
    dZ2 = dA2 * sigmoid_derivative(Z2)
    dW2 = np.dot(dZ2.T, A1)
    db2 = np.sum(dZ2, axis=0, keepdims=True)

    dA1 = np.dot(dZ2, W2)  # Backpropagate the error to A1
    dZ1 = dA1 * relu_derivative(Z1)
    dW1 = np.dot(X.T, dZ1)
    db1 = np.sum(dZ1, axis=0, keepdims=True)

    # Update weights and biases using gradient descent
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss}")

# Final weights and predictions
print(f"Trained Weights: W1={W1}, W2={W2}")
print(f"Trained Biases: b1={b1}, b2={b2}")
predictions = sigmoid(np.dot(relu(np.dot(X, W1) + b1), W2.T) + b2)
print("Predictions:", predictions)


Epoch 0, Loss: 523.8562455482468
Epoch 1000, Loss: 501.62006362696604
Epoch 2000, Loss: 501.6100172366035
Epoch 3000, Loss: 501.6066746744842
Epoch 4000, Loss: 501.6050046431813
Epoch 5000, Loss: 501.6040030406072
Epoch 6000, Loss: 501.60333548402986
Epoch 7000, Loss: 501.60285874730135
Epoch 8000, Loss: 501.6025012445525
Epoch 9000, Loss: 501.6022232168314
Trained Weights: W1=[[-0.01532005 -0.00127981 -0.17937778]
 [ 0.01175836 -0.02696044 -0.02534187]
 [-0.00116911  0.00844222 -0.01717751]], W2=[[-0.00611063 -0.00695132  0.00886325]]
Trained Biases: b1=[[ 0.          0.         -0.00641099]], b2=[[9.99834648]]
Predictions: [[0.99995453]
 [0.99995453]
 [0.99995453]
 [0.99995453]
 [0.99995453]]
